### PR TITLE
Removal of hs00.

### PR DESCRIPTION
**Pull request by SkyToGround**
### Issue

*Specify the associated JIRA ticket, e.g. DM-1234.*

### Description of work

*Add a description of the work done. The aim is provide information to help the reviewer review the PR efficiently.
See [CONTRIBUTING.MD](CONTRIBUTING.MD) for more information on code standards etc.*

### Nominate for Group Code Review

- [ ] Nominate for code review 

### Reminder

*Changes should be documented in `changes.md`*

### CODE REVIEW

**Comment by mkoennecke** [comment]
Why remove hs00 writing? There are use cases. I am not at all happy with this. Already at your ODIN there will be cameras streaming hs00 and that data needs to be stored. We have similar use cases at PSI

**Review by mkoennecke — CHANGES_REQUESTED** [review]
I request that hs00 writing stays. ESS will need it for writing area detector image data at ODIN. At PSI we will be using it to store histogrammed data together with the event data. I have a request to stream images against motor positions from our imaging people at PSI.

**Comment by zjttoefs** [comment]
ESS has no immediate confirmed use case. But know this is in use at PSI, so we should have Mark's approval for merging.
We've got no ticket for this as far as I can tell.

**Comment by SkyToGround** [comment]
I have two times asked PSI (though not specifically Mark) if hs00 was used and received the answer that it is not. With that said, we can leave the module to languish for a while longer. I will close the PR.

**Pull request closed without merging**
