### PR TITLE
DM-1481: add version information

### PR DESCRIPTION
**Pull request by amues**
### Issue

DM-1481

### Description of work

Add Versioning.cmake module for automated versioning according to the ECDC scheme and `--version` command-line flag for application version reporting.

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by matthew-d-jones** [comment]
@amues The system tests are picking up a genuine problem here. CLI11 gives an error if you try to run the application with a config file:
```
bin/kafka-to-nexus -c test_file_writer.ini
Expected exactly 1 arguments to --config-file, got 2
Run with --help for more information.
```
Maybe your extra call to `parse` is causing a problem?

**Comment by SkyToGround** [comment]
@amues @matthew-d-jones I think I have a solution to that issue. Give me a moment to test it.

**Comment by SkyToGround** [comment]
@amues @matthew-d-jones That appears to have done it!

**Comment by matthew-d-jones** [comment]
Thanks @SkyToGround

**Pull request merged**
