### PR TITLE
Optional SWMR support

### PR DESCRIPTION
**Pull request by dominikwerder**
### Description of work

HDF SWMR can be enabled by adding to the filewrite command:

```
{ "use_hdf_swmr": true }
```

### Issue

Closes https://jira.esss.lu.se/browse/DM-412
Closes https://jira.esss.lu.se/browse/DM-728

### Acceptance Criteria

Files should get written as normal.
SWMR reading could be added to the integration tests.

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

**Comment by dominikwerder** [comment]
According to the HDF presentation at the last ICALEPCS, the performance impact can be rather large, but this can be investigated in more detail.

Regarding the POSIX filesystem requirement: HDF does not say that SWMR writing works fine on a non-POSIX filesystem. How I read it, there could be not only inconsistent data on the reader side, but (for some reason I can not yet see) also the writing would not be guaranteed to work.

**Comment by matthew-d-jones** [comment]
If the intention is to always use SWMR at the ESS then it makes sense to make it the default so that our testing is done with it enabled etc.

I hope no one is using a non-POSIX compliant filesystem anyway. Everyone is using XFS, ZFS, NTFS, Lustre... right?

**Comment by matthew-d-jones** [comment]
oh APFS on OS X, is that POSIX compliant?

**Comment by SkyToGround** [comment]
I am very confident that APFS is POSIX compliant. Interesting fact: the old HFS+ file system used by MacOSX is (generally) not POSIX compliant, but that is due to the way lower and upper case letters are handled.

**Pull request merged**
