### PR TITLE
DM-1799 Implement new metrics system

### PR DESCRIPTION
**Pull request by SkyToGround**
### Issue

*Specify the associated JIRA ticket, e.g. DM-1234.*

### Description of work

*Add a description of the work done. The aim is provide information to help the reviewer review the PR efficiently.
See [CONTRIBUTING.MD](CONTRIBUTING.MD) for more information on code standards etc.*

### Nominate for Group Code Review

- [ ] Nominate for code review

### CODE REVIEW

**Comment by mattclarke** [comment]
Any chance of proper PR description? ;)

**Comment by mattclarke** [comment]
Just a general comment on the unit tests, their naming is a bit of a curate's egg: `DeRegisterFromGrafanaSuccess` gives me a much better idea of what the test is doing than `DeRegisterFail1`.
Could we have more of the former please?

**Comment by SkyToGround** [comment]
> Any chance of proper PR description? ;)

Not really I think. I noticed that no-one was reading those and you are the first person who comment on this after not having written any in ~8 months.

**Comment by SkyToGround** [comment]
> Just a general comment on the unit tests, their naming is a bit of a curate's egg: `DeRegisterFromGrafanaSuccess` gives me a much better idea of what the test is doing than `DeRegisterFail1`.
> Could we have more of the former please?

Sure I can be a bit more descriptive.

**Comment by mattclarke** [comment]
> > Any chance of proper PR description? ;)
> 
> Not really I think. I noticed that no-one was reading those and you are the first person who comment on this after not having written any in ~8 months.

That might be because I have only reviewed one of your tickets in the last 8 months ;)
I blame everyone else 😇

**Comment by SkyToGround** [comment]
This is now more or less a total re-write of the PR by @matthew-d-jones so (that I have accepted). I will merge it without further action.

**Pull request merged**
