### PR TITLE
Do not overwrite existing HDF file, but produce error instead

### PR DESCRIPTION
**Pull request by dominikwerder**
Do not overwrite existing HDF file, but produce error instead.

Adjust test cases to `unlink` an existing file before running the test.

Updates #116

### CODE REVIEW

**Comment by SkyToGround** [comment]
Although this behaviour is (possibly) a slight improvement over the previous implementation, this is NOT the way to go. Throwing an error if the file already exist is a somewhat hostile behaviour. The application should try to recover if possible. The better implementation is to check if the file exists and attempt to use another file name if it does. For example, the MacOSX Finder appends a number to the file name if the file already exist.

**Comment by dominikwerder** [comment]
@SkyToGround Thank you for your opinion. Regarding the PR, we first stop the overwrite. Whether or not we should try again with an automatic filename change should be configurable and will be addressed in another PR.

**Comment by SkyToGround** [comment]
@dominikwerder I can see no reasonable argument (other than writing less code) for not having the default behaviour be that the application tries to recover by using an alternative file name. Care to elaborate why you think throwing an error is better?

**Comment by zjttoefs** [comment]
Depends on who is in charge of the file name. As I understand it the filename is given to the writer. If that is not an acceptable choice, throwing an error is not unreasonable. The file could not be writable for other reasons (file system full or read-only) so dealing with errors is required.
If it was for the file writer to pick a working name in the first place, then I would agree with @SkyToGround.

**Comment by SkyToGround** [comment]
@zjttoefs I agree that if it is not possible to create a file in the specified directory then an error should be thrown. Although it is not up to the file writer to pick the file name, mistakes will be made and having the file writer attempt to recover from those mistakes as gracefully as possible and pick another file name is the better option. This way, the probability of data loss is minimised. See also #87.

Seeing as the safer option requires relatively little extra code (depending on how you decide to implement it), there is not much downside to writing the "correct" implementation.

**Pull request merged**
