### PR TITLE
Base docker image on alpine and add gcc 9 build

### PR DESCRIPTION
**Pull request by matthew-d-jones**
Base the docker image on Alpine 11, which has gcc 9.2.
Makes the image smaller and faster to build for system tests.

Also adds an alpine pipeline build, which will ensure we have package binaries on the conan server for the system test image to use. Having a gcc 9.2 build already should also mean those of us who run Ubuntu can switch to Ubuntu 20.04 LTS as soon as it is released in April.

Removed CentOS-debug and Debian10 builds.

### CODE REVIEW

**Comment by mchorazak** [comment]
# [Codecov](https://codecov.io/gh/ess-dmsc/kafka-to-nexus/pull/514?src=pr&el=h1) Report
> Merging [#514](https://codecov.io/gh/ess-dmsc/kafka-to-nexus/pull/514?src=pr&el=desc) into [v3.0.0](https://codecov.io/gh/ess-dmsc/kafka-to-nexus/commit/4ac68402672d76124e307cb93edb397a58f8fe1b&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.


```diff
@@           Coverage Diff           @@
##           v3.0.0     #514   +/-   ##
=======================================
  Coverage   68.24%   68.24%           
=======================================
  Files         109      109           
  Lines        3672     3672           
=======================================
  Hits         2506     2506           
  Misses       1166     1166           
```

**Comment by matthew-d-jones** [comment]
Will update Jenkinsfile to remove a couple of the builds in exchange for adding the alpine build.

**Comment by matthew-d-jones** [comment]
API test

**Comment by matthew-d-jones** [comment]
**Code Coverage**

**Comment by matthew-d-jones** [comment]
**Code Coverage**
                                           Lines    Exec  Cover
${coverage_summary}
*For more detail see Cobertura report in Jenkins interface)*

**Pull request merged**
