### PR TITLE
Adding CLI11 ini configuration file support

### LINKED ISSUE #275: Add CLI11 .ini files for startup configuration
and have command messages in separate json file referenced by .ini or as separate option.

### PR DESCRIPTION
**Pull request by rerpha**
### Description of work
(Breaking change to anything that uses configuration files currently)
This replaces the configuration JSON and adds anything that wasn't in the command line functionality to the command line options (besides librdkafka options for now) 

Test coverage will decrease slightly as the json parsing stuff has been removed. There is no easy way to test CLI11s functionality nor should we as it's an external library but unfortunately this means that some lines of code have been added and can't be covered. 

### Issue

Closes #275 

### Acceptance Criteria

Test that the filewriter still outputs files properly with manual tests/system tests if they are merged

### Unit Tests

Deleted any unit tests that test the functionality of checking for options in the previous json configuration files as CLI11 now handles this. 

### Other

Updated README.md to show new `.ini` file usage.

---

## Code Review (To be filled in by the reviewer only)

- [ ] Is the code of an acceptable quality?
- [ ] Do the changes function as described and is it robust?

---

## Nominate for Group Code Review (Anyone can nominate it)
Indicate if you think the code should be reviewed in a Thursday code review session.

- [ ] Recommend for group code review

Also, nominate it on the code_review Slack channel (does someone want to automate this?).

### CODE REVIEW

**Comment by rerpha** [comment]
Todo: add librdkakfa options

**Comment by rerpha** [comment]
Needs system tests updating

**Comment by dominikwerder** [comment]
Build fails on OSX. Was this accidentally merged?

**Comment by matthew-d-jones** [comment]
@dominikwerder The lastest commit on master has a successful build: https://jenkins.esss.dk/dm/blue/organizations/jenkins/ess-dmsc%2Fkafka-to-nexus/detail/287_missing_cli_opt/1/pipeline

**Comment by dominikwerder** [comment]
@matthew-d-jones The last commits in this PR failed to build, e.g. 40f7f2a. Interestingly, when I know click on the red cross left to the commit id, the Jenkins output which previously showed the build failures is no longer there, it gives 404 for me.

Anyway, when I merged my other branch with master and pushed that, Jenkins did the build successfully, so it was maybe a temporary problem with the build server.

**Comment by matthew-d-jones** [comment]
@SkyToGround Sounds like it was the one node passing in this case! I'm guess because it didn't get its disk full of docker images like the other nodes.

**Comment by SkyToGround** [comment]
Oh, ok.

**Pull request merged**
